apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: robot-shop
description: main application pipeline
serialPipeline:
 stages:
 - targetId: learn
   profiles: [learn]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: learn
description: learn env
gke:
 cluster: projects/TheDevProj/locations/us-central1-c/clusters/robot-shop-cluster